export FLASK_APP=app.py
export FLASK_ENV=development
export FLASK_RUN_HOST=0.0.0.0
export FLASK_RUN_PORT=5000
export MAIL_SERVER=smtp-mail.outlook.com
export MAIL_PORT=587
export MAIL_SECURITY_TYPE=starttls
export MAIL_USE_TLS=True
export MAIL_USE_SSL=False
export MAIL_USERNAME=nathanbrown-bennett@hotmail.com
export MAIL_PASSWORD=gstntfqokimbnlcp
flask run
