"""empty message

Revision ID: 352d790f92c6
Revises: 5fdf55abfb94
Create Date: 2024-08-29 18:12:46.028912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352d790f92c6'
down_revision = '5fdf55abfb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
